[tool.poetry]
name = "oldplotlib"
version = "0.1.0"
description = "A Matplotlib stylesheet to replicate the figure style of Changeux and Kittel"
authors = ["Guillaume David <guillaumedavidphd@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
matplotlib = ">=3.7.1"


[build-system]
requires = ["poetry-core", "matplotlib"]
build-backend = "poetry.core.masonry.api"
